# Step Function

In [13]:
import numpy as np

def step_function(x) :
    if x > 0 :
        return 1
    else :
        return 0

print(step_function(0))
print(step_function(2))
print(step_function(3.14))
# print(step_function(np.array([1.0, 2.0, 3.3])))

0
1
1


In [33]:
import numpy as np

def step_function(x):
    x = np.array(x)  # Ensure that x is a numpy array
    y = x > 0
    return y.astype(np.int32)

print(step_function(0))
print(step_function(2))
print(step_function(3.14))
print(step_function(np.array([1.0, 2.0, 3.3])))


0
1
1
[1 1 1]


# Sigmoid Function 

In [26]:
import numpy as np

def sigmoid(x) :
    return 1 / (1 + np.exp(-x))

x = np.array([-100.0, -1.0, 0.0, 1.0, 200.0])
sigmoid(x)

array([3.72007598e-44, 2.68941421e-01, 5.00000000e-01, 7.31058579e-01,
       1.00000000e+00])

# ReLU (Rectified Linear Unit)

In [35]:
def relu(x) :
    return np.maximum(0, x)

print(relu(-1))
print(relu(0))
print(relu(0.1))
print(relu(100))

0
0
0.1
100


# 두 행렬의 곱 : np.dot()

In [41]:
A = np.array([
    [1, 2], [3, 4], [5, 6]
])
B = np.array([7, 8])

print(A.shape)
print(B.shape)

print("A * B = "+ str(np.dot(A, B)))

(3, 2)
(2,)
A * B = [23 53 83]


# 각 층의 신호 전달 구현하기

In [6]:
import numpy as np

def sigmoid_function(x) :
    return 1 / (1 + np.exp(-x))
def identity_function(x) :
    return x

# 신경망 구현의 관례에 따라 가중치만 대문자(W)로 쓰고, 그 외 편향과 중간 결과 등은 모두 소문자로 작성.
def init_network() :
    network = {}
    network['W1'] = np.array([ [0.1, 0.3, 0.5], [0.2, 0.4, 0.6] ])
    network['b1'] = np.array([ 0.1, 0.2, 0.3 ])
    network['W2'] = np.array([ [0.1, 0.4], [0.2, 0.5], [0.3, 0.6] ])
    network['b2'] = np.array([ 0.1, 0.2 ])
    network['W3'] = np.array([ [0.1, 0.3], [0.2, 0.4] ])
    network['b3'] = np.array([ 0.1, 0.2 ])
    return network

# 신호가 순방향(입력에서 출력 방향)으로 전달됨(순전파)을 알리기 위해 forward()
# 신경망 학습을 다룰 때, 역방향(backward, 출력에서 입력 방향)처리도 있다.
def forward(network, x) :
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    # Layer 0 (Input Layer)
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid_function(a1)
    # Layer 1 (Hidden Layer)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid_function(a2)
    # Layer 2 (Output Layer)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    return y

network = init_network()
x = np.array( [1.0, 0.5] )
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


# Softmax Function

In [8]:
import numpy as np 

def softmax_function(a) :
    c = np.max(a)  # 입력 신호 중 최대값을 c
    exp_a = np.exp(a - c) # Overflow를 막기 위해 모든 입력 신호에서 최대값을 빼줌
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

a = np.array([ 0.3, 2.9, 4.0 ])
y = softmax_function(a)
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0
